version: '3.8'

services:
  # Gotenberg - PDF Generation Service
  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: criador_contrato_gotenberg
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - gotenberg_tmp:/tmp
      - ./pdf-templates:/app/templates:ro
    environment:
      # Security Configuration
      - GOTENBERG_API_PORT=3000
      - GOTENBERG_API_PORT_FROM_ENV=true
      - GOTENBERG_LOG_LEVEL=INFO
      - GOTENBERG_LOG_FORMAT=json
      
      # Resource Limits
      - GOTENBERG_CHROMIUM_TIMEOUT=30s
      - GOTENBERG_CHROMIUM_MAX_QUEUE_SIZE=100
      - GOTENBERG_CHROMIUM_AUTO_START=true
      - GOTENBERG_CHROMIUM_SCALE=1
      
      # PDF Generation Settings
      - GOTENBERG_CHROMIUM_DEFAULT_WAIT_DELAY=3s
      - GOTENBERG_CHROMIUM_DEFAULT_WAIT_FOR_SELECTOR=""
      - GOTENBERG_CHROMIUM_PAPER_WIDTH=8.5
      - GOTENBERG_CHROMIUM_PAPER_HEIGHT=11
      - GOTENBERG_CHROMIUM_MARGINS_TOP=0.39
      - GOTENBERG_CHROMIUM_MARGINS_BOTTOM=0.39
      - GOTENBERG_CHROMIUM_MARGINS_LEFT=0.39
      - GOTENBERG_CHROMIUM_MARGINS_RIGHT=0.39
      
      # Performance Optimization
      - GOTENBERG_CHROMIUM_DISABLE_JAVASCRIPT=false
      - GOTENBERG_CHROMIUM_DISABLE_WEB_SECURITY=false
      - GOTENBERG_CHROMIUM_DISABLE_PLUGINS=true
      - GOTENBERG_CHROMIUM_DISABLE_EXTENSIONS=true
    command: >
      gotenberg
      --chromium-auto-start
      --chromium-max-queue-size=100
      --api-timeout=60s
      --api-root-path=/
      --log-level=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - criador_contrato_network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # LibreOffice Service (for document conversion if needed)
  libreoffice:
    image: gotenberg/gotenberg:8
    container_name: criador_contrato_libreoffice
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - GOTENBERG_API_PORT=3000
      - GOTENBERG_LOG_LEVEL=INFO
      - GOTENBERG_LIBRE_OFFICE_AUTO_START=true
      - GOTENBERG_LIBRE_OFFICE_TIMEOUT=30s
    command: >
      gotenberg
      --libreoffice-auto-start
      --api-timeout=60s
      --log-level=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - criador_contrato_network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'

volumes:
  gotenberg_tmp:
    driver: local

networks:
  criador_contrato_network:
    external: true